#parent stack
AWSTemplateFormatVersion: "2010-09-09"
Description: "This is an scheduler resources infrastructure template."
Resources:
  RolesSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - https://${bucketUrl}.s3.eu-central-1.amazonaws.com/roles.yml
        - bucketUrl:
            Ref: DeploymentBucketUrl
#  BucketsSubStack:
#    Type: 'AWS::CloudFormation::Stack'
#    Properties:
#      TemplateURL: !Sub
#        - https://${bucketUrl}.s3.eu-central-1.amazonaws.com/buckets.yml
#        - bucketUrl:
#            Ref: DeploymentBucketUrl
  TablesSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - https://${bucketUrl}.s3.eu-central-1.amazonaws.com/dbTables.yml
        - bucketUrl:
            Ref: DeploymentBucketUrl
  LayersSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - https://${bucketUrl}.s3.eu-central-1.amazonaws.com/layers.yml
        - bucketUrl:
            Ref: DeploymentBucketUrl
  LambdasSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - https://${bucketUrl}.s3.eu-central-1.amazonaws.com/lambdas.yml
        - bucketUrl:
            Ref: DeploymentBucketUrl
      Parameters:
        BotRoleArn: !GetAtt RolesSubStack.Outputs.BotRoleArn
  QueuesSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - https://${bucketUrl}.s3.eu-central-1.amazonaws.com/queues.yml
        - bucketUrl:
            Ref: DeploymentBucketUrl
      Parameters:
        EventLambdaArn: !GetAtt LambdasSubStack.Outputs.EventProcessorArn
  ApiSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - https://${bucketUrl}.s3.eu-central-1.amazonaws.com/apis.yml
        - bucketUrl:
            Ref: DeploymentBucketUrl
      Parameters:
        BotLambdaName: !GetAtt LambdasSubStack.Outputs.BotLambdaName
        AuthLambdaName: !GetAtt LambdasSubStack.Outputs.AuthLambdaName
        UiLambdaName: !GetAtt LambdasSubStack.Outputs.UiLambdaName
        AuthLambdaArn: !GetAtt LambdasSubStack.Outputs.AuthLambdaArn
        UiLambdaArn: !GetAtt LambdasSubStack.Outputs.UiLambdaArn
        BotLambdaArn: !GetAtt LambdasSubStack.Outputs.BotLambdaArn
Parameters:
  DeploymentBucketUrl:
    Type: String

