#layers subStack
AWSTemplateFormatVersion: "2010-09-09"
Description: "This is a layers template."
Resources:
  BotLayer:
    Type: 'AWS::Lambda::LayerVersion'
    Properties:
      CompatibleRuntimes:
        - java11
#      Content:
#        S3Bucket:
#          Ref: LayerBucketName
#        S3Key:
#          Ref: LayerFileName
      Description: Bot lambdas 3rd party dependencies.
      LayerName:
        Ref: LayerName
Parameters:
  LayerBucketName:
    Type: String
    Default: layer-bucket-scheduler
  LayerFileName:
    Type: String
    Default: bot-layer-dependencies.jar
  LayerName:
    Type: String
    Default: 3rd-party-layer1